### ISSUE TITLE
Test different screen resolutions

### ISSUE THREAD

**Issue by MisterProper9000** [MisterProper9000/PeopleClickerInception#17]
Base screen resolutions: 2560x1440, 1920x1080, 1600x900, 1280x720, 2160x1080, 2248x1080, 3040x1440, 2220x1080 (we are testing on BlueStacks PC application and smartphones)

**Comment by mashaverdina** [comment]
Please describe minimal set of resolutions to check

**Comment by mashaverdina** [comment]
Checking resolution only for the same screen ratio (width/height) is not enough. For example Mi 8 has 2248x1080, Samsung S10 has 3040x1440, Samsung A7 has 2220х1080 and so on.

**Comment by MisterProper9000** [comment]
We also forgot 2160x1080 for 18:9 screen ratio.
