### ISSUE TITLE
Create and update ReleaseNotes.md

### ISSUE THREAD

**Issue by MisterProper9000** [MisterProper9000/PeopleClickerInception#30]

**Comment by mashaverdina** [comment]
Why there is no commit for this ticket?

**Comment by mashaverdina** [comment]
Let's use 3 digits as version's major.minor.patch
Something like https://semver.org/
Our major is always 0, this means that it's currently under development.

**Comment by sergeevgk** [comment]
This ticket has no referenced commit because at the time I created and commited release-notes.md there was #10 issue "Create release of Sprint 1" and I thought that release-notes must be referenced to #10. On update release-notes.md there will be reference to #30
