### ISSUE TITLE
Make mind-blowing presentation

### ISSUE THREAD

**Issue by MisterProper9000** [MisterProper9000/PeopleClickerInception#75]

**Comment by sergeevgk** [comment]
@SWAGLORD1 , посмотрите, пожалуйста, презентацию -- последняя версия лежит в pci_discuss, отправлена туда в 19 36

**Comment by MisterProper9000** [comment]
Залил исправленную версию в pci_discuss

**Comment by MisterProper9000** [comment]
@SWAGLORD1 Посмотрите пожалуйста исправленную версию
